schemaVersion: 2.2.0
metadata:
  name: CloudNativeAppDev
attributes:
  controller.devfile.io/storage-type: per-workspace
projects:
  - name: website
    git:
      remotes:
        origin: https://github.com/redhat-appdev-practice/website
components:
  - name: cloud-native-app-dev
    container:
      image: registry.redhat.io/devspaces/udi-rhel8
      mountSources: true
      endpoints:
        - name: vuepress
          protocol: http
          targetPort: 8080
