name: Build and Deploy
on:
  push:
    branches: trunk
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@trunk

    - name: Build and Deploy
      uses: testthedocs/github-pages-deploy-action@master
      env:
        BUILD_DIR: .vuepress/build/ # The folder, the action should deploy.
        BUILD_SCRIPT: npx vuepress build
